// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SessionConfig holds per-workflow session recording configuration.
 */
export class SessionConfig {
    /**
     * Creates a new SessionConfig instance.
     * @param {Partial<SessionConfig>} [$$source = {}] - The source object to create the SessionConfig.
     */
    constructor($$source = {}) {
        if (!("StoreRaw" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["StoreRaw"] = false;
        }
        if (!("StoreProcessed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["StoreProcessed"] = false;
        }
        if (!("MaxSessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxSessions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionConfig(/** @type {Partial<SessionConfig>} */($$parsedSource));
    }
}

/**
 * SessionMeta is a lightweight view of a session for listing purposes.
 */
export class SessionMeta {
    /**
     * Creates a new SessionMeta instance.
     * @param {Partial<SessionMeta>} [$$source = {}] - The source object to create the SessionMeta.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("StartTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["StartTime"] = 0;
        }
        if (!("EndTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["EndTime"] = 0;
        }
        if (!("EndReason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EndReason"] = "";
        }
        if (!("RawLayerEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RawLayerEnabled"] = false;
        }
        if (!("ProcessedLayerEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ProcessedLayerEnabled"] = false;
        }
        if (!("DataVolume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["DataVolume"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionMeta(/** @type {Partial<SessionMeta>} */($$parsedSource));
    }
}
