// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BlockCategory identifies the category of a pipeline block.
 * @readonly
 * @enum {string}
 */
export const BlockCategory = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CategoryInput: "input",
    CategoryProcessing: "processing",
    CategoryAnalysis: "analysis",
};

/**
 * FlowState represents the current state of the pipeline.
 * @readonly
 * @enum {string}
 */
export const FlowState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FlowStateIdle: "idle",
    FlowStateRunning: "running",
    FlowStatePaused: "paused",
    FlowStateError: "error",
};
