// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../internal/pipeline/models.js";

/**
 * BlockTypeDescriptor describes a registered block type for the frontend catalogue.
 */
export class BlockTypeDescriptor {
    /**
     * Creates a new BlockTypeDescriptor instance.
     * @param {Partial<BlockTypeDescriptor>} [$$source = {}] - The source object to create the BlockTypeDescriptor.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {pipeline$0.BlockCategory}
             */
            this["category"] = pipeline$0.BlockCategory.$zero;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("defaultParams" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["defaultParams"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockTypeDescriptor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockTypeDescriptor}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("defaultParams" in $$parsedSource) {
            $$parsedSource["defaultParams"] = $$createField4_0($$parsedSource["defaultParams"]);
        }
        return new BlockTypeDescriptor(/** @type {Partial<BlockTypeDescriptor>} */($$parsedSource));
    }
}

/**
 * PipelineService controls the pipeline runtime lifecycle.
 */
export class PipelineService {
    /**
     * Creates a new PipelineService instance.
     * @param {Partial<PipelineService>} [$$source = {}] - The source object to create the PipelineService.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PipelineService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PipelineService(/** @type {Partial<PipelineService>} */($$parsedSource));
    }
}

/**
 * PipelineStateGetter is a minimal interface to check pipeline state.
 * @typedef {any} PipelineStateGetter
 */

/**
 * SerialPortInfo describes a serial port available on the machine.
 */
export class SerialPortInfo {
    /**
     * Creates a new SerialPortInfo instance.
     * @param {Partial<SerialPortInfo>} [$$source = {}] - The source object to create the SerialPortInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("vendorId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vendorId"] = "";
        }
        if (!("productId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productId"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialPortInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SerialPortInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialPortInfo(/** @type {Partial<SerialPortInfo>} */($$parsedSource));
    }
}

/**
 * SessionService manages session lifecycle from the frontend's perspective.
 */
export class SessionService {
    /**
     * Creates a new SessionService instance.
     * @param {Partial<SessionService>} [$$source = {}] - The source object to create the SessionService.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionService instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionService}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionService(/** @type {Partial<SessionService>} */($$parsedSource));
    }
}

/**
 * StorageEstimate holds session storage stats.
 */
export class StorageEstimate {
    /**
     * Creates a new StorageEstimate instance.
     * @param {Partial<StorageEstimate>} [$$source = {}] - The source object to create the StorageEstimate.
     */
    constructor($$source = {}) {
        if (!("currentTotalBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentTotalBytes"] = 0;
        }
        if (!("averageSessionBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["averageSessionBytes"] = 0;
        }
        if (!("projectedMaxBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["projectedMaxBytes"] = 0;
        }
        if (!("warningThresholdBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["warningThresholdBytes"] = 0;
        }
        if (!("exceedsThreshold" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exceedsThreshold"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageEstimate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StorageEstimate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageEstimate(/** @type {Partial<StorageEstimate>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
