// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService controls the pipeline runtime lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../internal/pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBlockErrors returns a map of blockID → errorMessage.
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetBlockErrors() {
    return $Call.ByID(2236930778).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetState returns the current flow state.
 * @returns {$CancellablePromise<pipeline$0.FlowState>}
 */
export function GetState() {
    return $Call.ByID(1280576029);
}

/**
 * Pause suspends data flow.
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(1752088870);
}

/**
 * Resume resumes data flow after a pause.
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(3116091983);
}

/**
 * SetApp stores the Wails app reference for event emission.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1672728535, app);
}

/**
 * SetSessionService wires the SessionService for storage estimate checks.
 * @param {$models.SessionService | null} ss
 * @returns {$CancellablePromise<void>}
 */
export function SetSessionService(ss) {
    return $Call.ByID(1165460883, ss);
}

/**
 * Start validates the workflow DAG and starts the pipeline.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2958635232);
}

/**
 * Stop stops the pipeline and completes the active session.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2641168932);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
