// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService manages session lifecycle from the frontend's perspective.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../internal/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSession permanently deletes a session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(sessionID) {
    return $Call.ByID(1971464949, sessionID);
}

/**
 * GetActiveSessionID returns the ID of the currently active session.
 * @returns {$CancellablePromise<string>}
 */
export function GetActiveSessionID() {
    return $Call.ByID(3153878591);
}

/**
 * GetSessionConfig returns the current session recording configuration.
 * @returns {$CancellablePromise<session$0.SessionConfig>}
 */
export function GetSessionConfig() {
    return $Call.ByID(1644300454).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStorageEstimate returns current and projected session storage.
 * @returns {$CancellablePromise<$models.StorageEstimate>}
 */
export function GetStorageEstimate() {
    return $Call.ByID(523167095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListSessions returns session metadata for the current workflow.
 * @returns {$CancellablePromise<session$0.SessionMeta[]>}
 */
export function ListSessions() {
    return $Call.ByID(3213356629).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SetApp stores the Wails app reference for event emission.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1708222475, app);
}

/**
 * SetPipelineService allows cross-service state checks.
 * @param {$models.PipelineService | null} ps
 * @returns {$CancellablePromise<void>}
 */
export function SetPipelineService(ps) {
    return $Call.ByID(4122587253, ps);
}

/**
 * SetViewSession switches Analysis blocks to display data from a historical session.
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function SetViewSession(sessionID) {
    return $Call.ByID(1253630867, sessionID);
}

/**
 * UpdateSessionConfig updates the session recording configuration.
 * @param {session$0.SessionConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSessionConfig(cfg) {
    return $Call.ByID(2379064017, cfg);
}

// Private type creation functions
const $$createType0 = session$0.SessionConfig.createFrom;
const $$createType1 = $models.StorageEstimate.createFrom;
const $$createType2 = session$0.SessionMeta.createFrom;
const $$createType3 = $Create.Array($$createType2);
