// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkflowService manages the workflow definition exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workflow$0 from "../internal/workflow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBlock creates and registers a new block at the given canvas position.
 * @param {string} blockType
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<workflow$0.BlockDef>}
 */
export function AddBlock(blockType, x, y) {
    return $Call.ByID(895500387, blockType, x, y).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddConnection adds a connection between two block ports.
 * @param {string} fromBlockID
 * @param {string} fromPortID
 * @param {string} toBlockID
 * @param {string} toPortID
 * @returns {$CancellablePromise<workflow$0.ConnectionDef>}
 */
export function AddConnection(fromBlockID, fromPortID, toBlockID, toPortID) {
    return $Call.ByID(2704901506, fromBlockID, fromPortID, toBlockID, toPortID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAvailableBlockTypes returns the full catalogue of registered block types.
 * @returns {$CancellablePromise<$models.BlockTypeDescriptor[]>}
 */
export function GetAvailableBlockTypes() {
    return $Call.ByID(628770974).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCurrentWorkflow returns a pointer to the mutable current workflow (internal use).
 * @returns {$CancellablePromise<workflow$0.Workflow | null>}
 */
export function GetCurrentWorkflow() {
    return $Call.ByID(2519289571).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetWorkflow returns the currently loaded workflow.
 * @returns {$CancellablePromise<workflow$0.Workflow>}
 */
export function GetWorkflow() {
    return $Call.ByID(3649389744).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListSerialPorts enumerates available serial ports.
 * @returns {$CancellablePromise<$models.SerialPortInfo[]>}
 */
export function ListSerialPorts() {
    return $Call.ByID(1709359889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * LoadWorkflow loads a workflow from a .byteflow file.
 * @param {string} path
 * @returns {$CancellablePromise<workflow$0.Workflow>}
 */
export function LoadWorkflow(path) {
    return $Call.ByID(2067635914, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RecoverWorkflow attempts to open a corrupted .byteflow file by re-initialising
 * the schema (discarding sessions) and returning an empty workflow for the file (T106).
 * @param {string} path
 * @returns {$CancellablePromise<workflow$0.Workflow>}
 */
export function RecoverWorkflow(path) {
    return $Call.ByID(1762072692, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RemoveBlock removes a block and its attached connections.
 * @param {string} blockID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveBlock(blockID) {
    return $Call.ByID(1176355360, blockID);
}

/**
 * RemoveConnection removes a connection by ID.
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnection(connectionID) {
    return $Call.ByID(3666586983, connectionID);
}

/**
 * SaveWorkflow persists the current workflow to a .byteflow file.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkflow(path) {
    return $Call.ByID(1850085247, path);
}

/**
 * SetCurrentWorkflow replaces the in-memory workflow.
 * @param {workflow$0.Workflow | null} wf
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrentWorkflow(wf) {
    return $Call.ByID(3440665727, wf);
}

/**
 * SetEngine sets the pipeline state getter (to enforce editing locks).
 * @param {$models.PipelineStateGetter} e
 * @returns {$CancellablePromise<void>}
 */
export function SetEngine(e) {
    return $Call.ByID(2080017855, e);
}

/**
 * UpdateBlockParams updates block parameters.
 * @param {string} blockID
 * @param {{ [_ in string]?: any }} params
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBlockParams(blockID, params) {
    return $Call.ByID(2085145541, blockID, params);
}

/**
 * UpdateBlockPosition updates the canvas position of a block.
 * @param {string} blockID
 * @param {number} x
 * @param {number} y
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBlockPosition(blockID, x, y) {
    return $Call.ByID(4033328980, blockID, x, y);
}

// Private type creation functions
const $$createType0 = workflow$0.BlockDef.createFrom;
const $$createType1 = workflow$0.ConnectionDef.createFrom;
const $$createType2 = $models.BlockTypeDescriptor.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = workflow$0.Workflow.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.SerialPortInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
