// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BlockDef is the persisted representation of a block in a workflow.
 */
export class BlockDef {
    /**
     * Creates a new BlockDef instance.
     * @param {Partial<BlockDef>} [$$source = {}] - The source object to create the BlockDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["params"] = {};
        }
        if (!("positionX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["positionX"] = 0;
        }
        if (!("positionY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["positionY"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BlockDef}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        return new BlockDef(/** @type {Partial<BlockDef>} */($$parsedSource));
    }
}

/**
 * ConnectionDef is the persisted representation of a connection in a workflow.
 */
export class ConnectionDef {
    /**
     * Creates a new ConnectionDef instance.
     * @param {Partial<ConnectionDef>} [$$source = {}] - The source object to create the ConnectionDef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("fromBlockId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromBlockId"] = "";
        }
        if (!("fromPortId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromPortId"] = "";
        }
        if (!("toBlockId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toBlockId"] = "";
        }
        if (!("toPortId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toPortId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionDef(/** @type {Partial<ConnectionDef>} */($$parsedSource));
    }
}

/**
 * SessionConfig holds per-workflow session recording configuration.
 */
export class SessionConfig {
    /**
     * Creates a new SessionConfig instance.
     * @param {Partial<SessionConfig>} [$$source = {}] - The source object to create the SessionConfig.
     */
    constructor($$source = {}) {
        if (!("storeRaw" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["storeRaw"] = false;
        }
        if (!("storeProcessed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["storeProcessed"] = false;
        }
        if (!("maxSessions" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxSessions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionConfig(/** @type {Partial<SessionConfig>} */($$parsedSource));
    }
}

/**
 * Workflow is the top-level container for the canvas definition, JSON-serialisable.
 */
export class Workflow {
    /**
     * Creates a new Workflow instance.
     * @param {Partial<Workflow>} [$$source = {}] - The source object to create the Workflow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("blocks" in $$source)) {
            /**
             * @member
             * @type {BlockDef[]}
             */
            this["blocks"] = [];
        }
        if (!("connections" in $$source)) {
            /**
             * @member
             * @type {ConnectionDef[]}
             */
            this["connections"] = [];
        }
        if (!("sessionConfig" in $$source)) {
            /**
             * @member
             * @type {SessionConfig}
             */
            this["sessionConfig"] = (new SessionConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Workflow}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField4_0($$parsedSource["blocks"]);
        }
        if ("connections" in $$parsedSource) {
            $$parsedSource["connections"] = $$createField5_0($$parsedSource["connections"]);
        }
        if ("sessionConfig" in $$parsedSource) {
            $$parsedSource["sessionConfig"] = $$createField6_0($$parsedSource["sessionConfig"]);
        }
        return new Workflow(/** @type {Partial<Workflow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = BlockDef.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ConnectionDef.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SessionConfig.createFrom;
